# Generated by Django 3.2.6 on 2021-08-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='uid',
            field=models.CharField(default=0, max_length=70),
        ),
    ]
